application: spellitserver
version: 1
runtime: python27
threadsafe: yes
api_version: 1

libraries:
- name: lxml
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: .*
  script: spellit.app.application
  secure: always
